[package]
name = "pig"
description = "A very simple PostgreSQL data migration tool."
version = "0.0.1"
authors = ["richardanaya"]
license = "MIT"
repository = "https://github.com/richardanaya/pig"


[dependencies]
quicli = "0.3"
postgres = "0.15"
chrono = "0.4.6"
